### ISSUE TITLE
OpenIdAuthenticationMechanism.getOriginalUrl(OpenIdAuthenticationMechanism.java:311): java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by pdbs** [eclipse-ee4j/soteria#339]
In Glassfish 7.0.0 M9 I sometimes get this stack trace while accessing a webpage in the middle of the loading process of several files:

`
[2022-10-25T16:54:39.257765+02:00] [GlassFish 7.0] [SEVERE] [] [jakarta.enterprise.system.container.web.com.sun.web.security] [tid: _ThreadID=39 _ThreadName=http-listener-2(4)] [levelValue: 1000] [[
  Jakarta Authentication: Exception during validateRequest
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:143)
        at org.glassfish.soteria.mechanisms.OpenIdAuthenticationMechanism.getOriginalUrl(OpenIdAuthenticationMechanism.java:311)
        at org.glassfish.soteria.mechanisms.OpenIdAuthenticationMechanism.authenticate(OpenIdAuthenticationMechanism.java:242)
        at org.glassfish.soteria.mechanisms.OpenIdAuthenticationMechanism.validateRequest(OpenIdAuthenticationMechanism.java:176)
        at org.glassfish.soteria.mechanisms.OpenIdAuthenticationMechanism$Proxy$_$$_WeldClientProxy.validateRequest(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
        at org.jboss.weld.generated.proxies.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism$152184814$Proxy$_$$_WeldClientProxy.validateRequest(Unknown Source)
        at org.glassfish.soteria.mechanisms.jaspic.HttpBridgeServerAuthModule.validateRequest(HttpBridgeServerAuthModule.java:89)
        at com.sun.jaspic.config.factory.singlemodule.DefaultServerAuthContext.validateRequest(DefaultServerAuthContext.java:54)
        at com.sun.web.security.RealmAdapter.validate(RealmAdapter.java:1336)
        at com.sun.web.security.RealmAdapter.invokeAuthenticateDelegate(RealmAdapter.java:480)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:554)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:579)
        at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:555)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:73)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:121)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:294)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:187)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:833)
]]
`

The OIDC token or authentication can not be the issue since multiple files (images, js, css) are loaded correctly, but in rare circumstances OpenIdAuthenticationMechanism fails with NoSuchElementException and I have no idea why.

The .get()-Method is throwing the error - and the comment says "checked before":

`               HttpStorageController.getInstance(configuration, request, response).getAsString(ORIGINAL_REQUEST).get(); // checked before
`

Maybe the check fails?

**Comment by pdbs** [comment]
It seems that the error is caused by either long timeouts using a proxy (which can be adjusted by jwksConnectTimeout & jwksReadTimeout) and redirectToOriginalResource. Redirecting to a callback URI seems to work.

**Comment by pdbs** [comment]
increasing timeouts with jwksConnectTimeout / jwksConnectTimeoutExpression did not solve the problem - same with Glassfish M10. I am trying to figure out whether Traefik is the issue.

**Comment by pdbs** [comment]
It seems a callback error upon redeploy of application. Not related to OpenIdAuthenticationMechanism
