### ISSUE TITLE
NPE BeanManager

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/soteria#340]
The Lookup can end with returning null or throwing an NamingException. The rest of the code should expect that, but doesn't, so I am seeing this in GlassFish's server.log while running the TCK. Despite that all tests passed.

```
[2022-11-08T17:52:17.540112+01:00] [GlassFish 7.0] [SEVERE] [] [jakarta.enterprise.web.core] [tid: _ThreadID=121 _ThreadName=AutoDeployer] [levelValue: 1000] [[
Error invoking ServletContainerInitializer org.glassfish.soteria.servlet.SamRegistrationInstaller
java.lang.NullPointerException: Cannot invoke "jakarta.enterprise.inject.spi.BeanManager.getBeans(java.lang.reflect.Type, java.lang.annotation.Annotation[])" because "beanManager" is null
at org.glassfish.soteria.cdi.CdiUtils.getBeanReferenceByType(CdiUtils.java:141)
at org.glassfish.soteria.cdi.CdiUtils.getBeanReference(CdiUtils.java:134)
at org.glassfish.soteria.servlet.SamRegistrationInstaller.onStartup(SamRegistrationInstaller.java:81)
at org.apache.catalina.core.StandardContext.callServletContainerInitializers(StandardContext.java:5282)
at com.sun.enterprise.web.WebModule.callServletContainerInitializers(WebModule.java:629)
at org.apache.catalina.core.StandardContext.start(StandardContext.java:5182)
at com.sun.enterprise.web.WebModule.start(WebModule.java:551)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:877)
at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:144)
at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:134)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:858)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:644)
at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1796)
at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1484)
at com.sun.enterprise.web.WebApplication.start(WebApplication.java:88)
at org.glassfish.internal.data.EngineRef.start(EngineRef.java:97)
at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:262)
at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:353)
at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:535)
```

**Comment by dmatej** [comment]
I am working on a PR ...
